"""Daily-digest email template renderer and open-flags query helper (Kanban #1217).

Two responsibilities:
1. Template rendering: `render_subject`, `render_text`, `render_html`.
2. Open-flags query: `fetch_open_audit_flags` — flag task summaries across
   all active (non-killed, non-paused) projects.

Template design constraints (spam hygiene): no external images/tracking pixels,
minimal inline CSS, plaintext alternative mirrors HTML.
Deep links: `/review?flag=<id>` served at `web/app/review/page.tsx`.
"""

from __future__ import annotations

import logging
from datetime import date as _date
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.constants import RecordStatus, TaskInteractionKind, TaskStatus
from src.models.project import Project
from src.models.task import Task

logger = logging.getLogger(__name__)

# Deep-link path — must match web/app/review/page.tsx route.
_FLAG_DEEP_LINK_PATH = "/review?flag={id}"


def render_subject(flag_count: int, date: _date | str) -> str:
    """Build the email subject line.

    Examples:
        "Digest 2026-05-22 — 3 open flags"
        "Digest 2026-05-22 — no open flags"
    """
    date_str = str(date)
    if flag_count == 0:
        return f"Digest {date_str} — no open flags"
    noun = "flag" if flag_count == 1 else "flags"
    return f"Digest {date_str} — {flag_count} open {noun}"


def _unpack_flag(flag: dict[str, Any], base_url: str) -> tuple[Any, str, str, Any, str, str, str]:
    """Extract the 7 display fields from a flag dict + compose the deep link."""
    fid = flag.get("id", "?")
    project = flag.get("project", "?")
    title = str(flag.get("title", ""))[:120]
    streak = flag.get("streak", 1)
    severity = flag.get("severity") or "unspecified"
    verdict = flag.get("verdict") or "review"
    link = base_url + _FLAG_DEEP_LINK_PATH.format(id=fid)
    return fid, project, title, streak, severity, verdict, link


def render_text(payload: dict[str, Any]) -> str:
    """Render the digest as plain text."""
    date_str = payload.get("date", "")
    flags: list[dict[str, Any]] = payload.get("flags") or []
    base_url = (payload.get("base_url") or "").rstrip("/")

    lines: list[str] = [
        f"Agent-Teams Daily Digest — {date_str}",
        "=" * 40,
        "",
    ]

    if not flags:
        lines += ["No open audit flags today.", ""]
    else:
        lines.append(f"Open audit flags ({len(flags)}):")
        for flag in flags:
            fid, project, title, streak, severity, verdict, link = _unpack_flag(flag, base_url)
            lines.append(
                f"  - [#{fid}] {project}: {title}"
                f" (streak={streak}, severity={severity}, verdict={verdict})"
            )
            lines.append(f"    Deep link: {link}")
        lines.append("")

    lines += [
        "--",
        "This digest was generated by agent-teams.",
        "Manage notification settings via DIGEST_EMAIL_ENABLED env var.",
    ]
    return "\n".join(lines)


def render_html(payload: dict[str, Any]) -> str:
    """Render the digest as minimal HTML suitable for email delivery."""
    date_str = payload.get("date", "")
    flags: list[dict[str, Any]] = payload.get("flags") or []
    base_url = (payload.get("base_url") or "").rstrip("/")

    parts: list[str] = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        f"<title>Agent-Teams Digest {_esc(date_str)}</title>",
        "</head>",
        '<body style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #222; max-width: 600px; margin: 0 auto; padding: 16px;">',
        f'<h1 style="font-size: 18px; color: #333; border-bottom: 1px solid #ddd; padding-bottom: 8px;">Agent-Teams Daily Digest &mdash; {_esc(date_str)}</h1>',
    ]

    if not flags:
        parts.append("<p>No open audit flags today.</p>")
    else:
        parts.append(f"<p><strong>Open audit flags ({len(flags)}):</strong></p>")
        parts.append('<table style="width:100%; border-collapse:collapse;">')
        for flag in flags:
            fid, project, title, streak, severity, verdict, link = _unpack_flag(flag, base_url)
            parts.append('<tr><td style="padding: 8px 0; border-bottom: 1px solid #eee;">')
            parts.append(
                f'<strong>[#{fid}] {_esc(project)}:</strong> {_esc(title)}'
            )
            parts.append(
                f'<br><span style="font-size: 12px; color: #777;">'
                f"streak={streak}, severity={_esc(severity)}, verdict={_esc(verdict)}"
                f"</span>"
            )
            parts.append(
                f'<br><a href="{_esc(link)}" style="color: #1a73e8;">Review flag #{fid}</a>'
            )
            parts.append("</td></tr>")
        parts.append("</table>")

    parts += [
        '<p style="font-size: 12px; color: #aaa; margin-top: 24px; border-top: 1px solid #eee; padding-top: 8px;">',
        "This digest was generated by agent-teams.<br>",
        "Manage settings via <code>DIGEST_EMAIL_ENABLED</code> env var.",
        "</p>",
        "</body>",
        "</html>",
    ]
    return "\n".join(parts)


def render_push_title(flag_count: int, date: _date | str) -> str:
    """Build a short push-notification title (≤ 80 chars).

    ASCII-only: title flows into ntfy's X-Title HTTP header which rejects
    non-ASCII characters (UnicodeEncodeError on em-dash — Kanban #1218).

    Examples:
        "Agent-Teams digest - 3 flag(s)"
        "Agent-Teams digest - all clear"
    """
    if flag_count == 0:
        return "Agent-Teams digest - all clear"
    noun = "flag" if flag_count == 1 else "flags"
    return f"Agent-Teams digest - {flag_count} {noun}"


def render_push_body(flags: list[Any], top_n: int = 3) -> str:
    """Build a short push-notification body (1-2 sentences, ≤ ~200 chars).

    Lists up to `top_n` project names with per-project flag counts; appends
    an overflow note when there are more. Returns "All clear — no open flags."
    when the list is empty.

    Examples (flags from 3 distinct projects, top_n=3):
        "Open flags: proj-a (2), proj-b (1), proj-c (1)."
        "Open flags: proj-a (2), proj-b (1), proj-c (1). +1 more project."
    """
    if not flags:
        return "All clear — no open flags."

    # Aggregate per project (order-stable — flags are sorted project_id ASC).
    project_counts: dict[str, int] = {}
    for flag in flags:
        name = str(flag.get("project", "?"))
        project_counts[name] = project_counts.get(name, 0) + 1

    projects = list(project_counts.items())  # [(name, count), ...]
    shown = projects[:top_n]
    overflow = len(projects) - len(shown)

    parts = ", ".join(f"{name} ({cnt})" for name, cnt in shown)
    body = f"Open flags: {parts}."
    if overflow > 0:
        noun = "project" if overflow == 1 else "projects"
        body += f" +{overflow} more {noun}."
    return body


def _esc(text: str) -> str:
    """Minimal HTML entity escaping for text inserted into HTML attributes/content."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


# ---------------------------------------------------------------------------
# Open-flags query helper
# ---------------------------------------------------------------------------


async def fetch_open_audit_flags(
    session: AsyncSession,
) -> list[dict[str, Any]]:
    """Return open AA3 audit-flag task summaries across active projects.

    "Active" means: project.status=1, NOT is_killed, NOT is_paused.
    "Open flag" means: task is an AA3 audit-flag question task with
      process_status IN {TODO, IN_PROGRESS, REVIEW, BLOCKED} AND status=1
      AND question_payload->>'is_audit_flag' = 'true'.

    Returns a list of dicts shaped for use as `payload['flags']` in
    render_text / render_html:
        id       : int
        project  : str
        title    : str
        streak   : int   — breach_streak_days; 1 when missing
        severity : str
        verdict  : str

    Sorted by project_id ASC, task.id ASC (deterministic).
    """
    stmt = (
        select(Task, Project)
        .join(Project, Task.project_id == Project.id)
        .where(
            # Project guards — active, not killed, not paused.
            Project.status == RecordStatus.ACTIVE,
            Project.is_killed.is_(False),
            Project.is_paused.is_(False),
            # Task guards — open AA3 flag.
            Task.status == RecordStatus.ACTIVE,
            Task.interaction_kind == TaskInteractionKind.QUESTION,
            Task.process_status.in_(
                [TaskStatus.TODO, TaskStatus.IN_PROGRESS, TaskStatus.REVIEW, TaskStatus.BLOCKED]
            ),
            Task.question_payload["is_audit_flag"].astext == "true",
        )
        .order_by(Task.project_id.asc(), Task.id.asc())
    )
    rows = (await session.execute(stmt)).all()

    flags: list[dict[str, Any]] = []
    for task, project in rows:
        qp = task.question_payload or {}
        latest_summary = qp.get("latest_audit_summary") or {}
        flags.append(
            {
                "id": task.id,
                "project": project.name,
                "title": task.title or "",
                "streak": int(qp.get("breach_streak_days") or 1),
                "severity": latest_summary.get("severity") or "unspecified",
                "verdict": latest_summary.get("verdict") or "review",
            }
        )
    return flags
